#!/bin/bash

config_file_folder="${HOME}/.config/gitb"
verbose_mode=false
show_help=false
action=""
project=""
branch_for_pull="master"
pull_only_master=
branch_delete=false
target_dir="${PROJECT_ROOT_PATH}/"

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case $1 in
  -v)
    verbose_mode=true
    shift
    ;;
  -h | --help | help)
    show_help=true
    shift
    ;;
  -r | --repository-folder)
    target_dir=${2}
    shift
    shift
    ;;
  -c | --config-file-folder)
    config_file_folder=${2}
    shift
    shift
    ;;
  -d | --delete)
    branch_delete=true
    shift
    ;;
  -b | --branch | -b=* | --branch=*)
    # TODO: remove support of "=" options
    if [[ ${1} == "-b" || ${1} == "--branch" ]]; then
      branch_for_pull="${2}"
      shift
    else
      branch_for_pull="${1#*=}"
    fi
    shift
    ;;
  -om | --only-master)
    if [[ ${2} == "1" || ${2} == "0" ]]; then
      pull_only_master=${2}
      shift
      shift
    fi
    ;;
  clone | pull | branch)
    action=${1}
    shift
    ;;
  *)
    project=${1}
    shift
    ;;
  esac
done
set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

function debug()
{
  if [ -n "$1" ]
  then
      IN="$@"
  else
      read IN # This reads a string from stdin and stores it in a variable called IN
  fi
  [[ ${verbose_mode} == true ]] && echod "${IN}"
}

function help() {
  echo ""
  echo "Usage: gitb COMMAND [project]"
  echo ""
  echo "Perform GIT actions on multiple repositories"
  echo ""
  echo "Options:"
  echo "  -v                                verbose mode"
  echo "  -r,  --repository-folder string   folder where the project repositories are (default is the PROJECT_ROOT_PATH env variable)"
  echo "  -c,  --config-file-folder string  folder where the project configuration file is (default is ~/.config/gitb/)"
  case "$action" in
    clone)
      ;;
    branch)
  echo "  -d,  --delete                     Remove local branches, except the default one"
  echo "  -om, --only-master 0|1            list only master or not master"
      ;;
    pull)
  echo "  -b,  --branch string              branch to pull (default is master)"
      ;;
  esac
  echo ""
  echo "Commands:"
  echo "  clone   Clone repositories"
  echo "  branch  Execute commands on local branches"
  echo "  pull    Pull changes if the branch is master"
  echo "  help    Print this helper"

  exit 0
}

function ensure_project() {
  project="${1}"

  if [[ ! -f ${project_config_file} ]]; then
    echoe "Project file is missing (${project_config_file}), pls create it"
    exit 1
  fi
}

function clone() {
  while IFS= read -r repository; do
    bn=$(basename $repository)
    filename=${bn%.*}

    cloneInto="${target_dir}${filename}"

    if [[ -d ${cloneInto} ]]; then
      echoi "already cloned: ${bn}"
    else
      echoi "cloning: ${bn}"
      git clone ${repository} ${cloneInto}
      echoi "cloning done: ${bn}"
    fi
  done <${project_config_file}
}

function pull() {
  while IFS= read -r repository; do
    bn=$(basename $repository)
    filename=${bn%.*}

    appFolder="${target_dir}${filename}"

    if [[ ! -d ${appFolder} ]]; then
      echow "${bn} | App is not cloned yet, skipped"
    elif [[ $(git -C ${appFolder} rev-parse --abbrev-ref HEAD) = "master" ]]; then
      echoi "${bn} | Branch is master, pulling"
      git -C ${appFolder} pull | debug "$@"
    else
      echow "${bn} | Branch is not master, skipped"
    fi
  done <${project_config_file}
}

function list() {
  while IFS= read -r repository; do
    bn=$(basename $repository)
    filename=${bn%.*}

    appFolder="${target_dir}${filename}"
    if [[ ! -d ${appFolder} ]]; then
      echow "${bn} | App is not cloned yet, skipped"
    else
      branch=$(git -C ${appFolder} rev-parse --abbrev-ref HEAD)
      if [[ (${branch} == "master" && ${pull_only_master} == "1") || (${branch} != "master" && ${pull_only_master} == "0") || ! ${pull_only_master} ]]; then
        echoi "App: ${bn}[$(git -C ${appFolder} rev-parse --abbrev-ref HEAD)]"
      fi
    fi

  done <${project_config_file}
}

function branch()
{
  if [[ ${branch_delete} == false ]]; then
    list
    return
  fi

  if [[ ${branch_delete} == true ]]; then
    while IFS= read -r repository; do
      bn=$(basename $repository)
      filename=${bn%.*}

      app_folder="${target_dir}${filename}"
      cd ${app_folder}
      git_local_branch_removal
      echoi "${filename} is done"
    done <${project_config_file}
  fi
}

project_config_file="${config_file_folder}/${project}"

debug "            Command > ${action}"
debug "            Project > ${project}"
debug " Config file folder > ${config_file_folder}"
debug "Project config file > ${project_config_file}"
debug "         Target DIR > ${target_dir}"
debug "    Branch for pull > ${branch_for_pull}"
debug "        Onyl master > ${pull_only_master}"

[[ ${show_help} == true ]] && help

case "$action" in
  clone)
    ensure_project ${project}
    clone
    ;;
  pull)
    ensure_project ${project}
    pull
    ;;
  branch)
    ensure_project ${project}
    branch 
    ;;
  *)
    help
    ;;
esac
